app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    link-check-delay: 50s
  client:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com/2.3
    bot: http://localhost:8090
  rate-limit:
    cache-size: 10_000
    expire-after-access: 2h
    refill-rate: 100
    refill-time-seconds: 3600
    capacity: 100
  database-access-type: jdbc
  git-hub-token: ${GIT_HUB_TOKEN}
  kafka-config-info:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    updates-topic:
      name: scrapper.updates
      partitions: 2
      replicas: 2
  use-queue: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: scrapper
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root1234}
  liquibase:
    enabled: false

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml
