app:
  telegram-token: ${BOT_TOKEN}
  command:
    description:
      start: start using the bot
  update-message: ${update-message:The link %s has recent updates :%s}
  scrapper:
    route: http://localhost:8080


spring:
  application:
    name: bot
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

