app:
  telegram-token: ${BOT_TOKEN}
  update-message: ${update-message:The link %s has recent updates :%s}
  kafka-config-info:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    updates-topic:
      name: scrapper.updates
      partitions: 2
      replicas: 2

spring:
  application:
    name: bot
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: UTC
  micrometer:
    processed-messages-counter:
      name: messages.processed
      description: number of processed messages

server:
  port: 8090

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml

