command:
  description:
    start: start using the bot

app:
  telegram-token: ${BOT_TOKEN}

spring:
  application:
    name: bot
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

