/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.records;


import edu.java.scrapper.domain.jooq.tables.Assignment;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AssignmentRecord extends UpdatableRecordImpl<AssignmentRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ASSIGNMENT.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ASSIGNMENT.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ASSIGNMENT.CHAT_ID</code>.
     */
    public void setChatId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ASSIGNMENT.CHAT_ID</code>.
     */
    @Nullable
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ASSIGNMENT.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ASSIGNMENT.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Assignment.ASSIGNMENT.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Assignment.ASSIGNMENT.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Assignment.ASSIGNMENT.LINK_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long component3() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long value3() {
        return getLinkId();
    }

    @Override
    @NotNull
    public AssignmentRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public AssignmentRecord value2(@Nullable Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public AssignmentRecord value3(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public AssignmentRecord values(@Nullable Long value1, @Nullable Long value2, @Nullable Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentRecord
     */
    public AssignmentRecord() {
        super(Assignment.ASSIGNMENT);
    }

    /**
     * Create a detached, initialised AssignmentRecord
     */
    @ConstructorProperties({ "id", "chatId", "linkId" })
    public AssignmentRecord(@Nullable Long id, @Nullable Long chatId, @Nullable Long linkId) {
        super(Assignment.ASSIGNMENT);

        setId(id);
        setChatId(chatId);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AssignmentRecord
     */
    public AssignmentRecord(edu.java.scrapper.domain.jooq.tables.pojos.Assignment value) {
        super(Assignment.ASSIGNMENT);

        if (value != null) {
            setId(value.getId());
            setChatId(value.getChatId());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
