/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.records;


import edu.java.scrapper.domain.jooq.tables.Links;

import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinksRecord extends UpdatableRecordImpl<LinksRecord> implements Record5<Long, String, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKS.URI</code>.
     */
    public void setUri(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS.URI</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 256)
    @NotNull
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINKS.HOST</code>.
     */
    public void setHost(@NotNull String value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKS.HOST</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 16)
    @NotNull
    public String getHost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>LINKS.PROTOCOL</code>.
     */
    public void setProtocol(@NotNull String value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINKS.PROTOCOL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 16)
    @NotNull
    public String getProtocol() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LINKS.LAST_UPDATED_AT</code>.
     */
    public void setLastUpdatedAt(@Nullable OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINKS.LAST_UPDATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getLastUpdatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Long, String, String, String, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row5<Long, String, String, String, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Links.LINKS.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Links.LINKS.URI;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return Links.LINKS.HOST;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return Links.LINKS.PROTOCOL;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field5() {
        return Links.LINKS.LAST_UPDATED_AT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUri();
    }

    @Override
    @NotNull
    public String component3() {
        return getHost();
    }

    @Override
    @NotNull
    public String component4() {
        return getProtocol();
    }

    @Override
    @Nullable
    public OffsetDateTime component5() {
        return getLastUpdatedAt();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUri();
    }

    @Override
    @NotNull
    public String value3() {
        return getHost();
    }

    @Override
    @NotNull
    public String value4() {
        return getProtocol();
    }

    @Override
    @Nullable
    public OffsetDateTime value5() {
        return getLastUpdatedAt();
    }

    @Override
    @NotNull
    public LinksRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value2(@NotNull String value) {
        setUri(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value3(@NotNull String value) {
        setHost(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value4(@NotNull String value) {
        setProtocol(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value5(@Nullable OffsetDateTime value) {
        setLastUpdatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord values(@Nullable Long value1, @NotNull String value2, @NotNull String value3, @NotNull String value4, @Nullable OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksRecord
     */
    public LinksRecord() {
        super(Links.LINKS);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    @ConstructorProperties({ "id", "uri", "host", "protocol", "lastUpdatedAt" })
    public LinksRecord(@Nullable Long id, @NotNull String uri, @NotNull String host, @NotNull String protocol, @Nullable OffsetDateTime lastUpdatedAt) {
        super(Links.LINKS);

        setId(id);
        setUri(uri);
        setHost(host);
        setProtocol(protocol);
        setLastUpdatedAt(lastUpdatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    public LinksRecord(edu.java.scrapper.domain.jooq.tables.pojos.Links value) {
        super(Links.LINKS);

        if (value != null) {
            setId(value.getId());
            setUri(value.getUri());
            setHost(value.getHost());
            setProtocol(value.getProtocol());
            setLastUpdatedAt(value.getLastUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
