/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.records;


import edu.java.scrapper.domain.jooq.tables.StackoverflowLinks;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowLinksRecord extends UpdatableRecordImpl<StackoverflowLinksRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ANSWER_COUNT</code>.
     */
    @Nullable
    public Long getAnswerCount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.SCORE</code>.
     */
    public void setScore(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.SCORE</code>.
     */
    @Nullable
    public Long getScore() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.ANSWER_COUNT;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.SCORE;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long component3() {
        return getScore();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long value3() {
        return getScore();
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value2(@Nullable Long value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value3(@Nullable Long value) {
        setScore(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord values(@NotNull Long value1, @Nullable Long value2, @Nullable Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StackoverflowLinksRecord
     */
    public StackoverflowLinksRecord() {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);
    }

    /**
     * Create a detached, initialised StackoverflowLinksRecord
     */
    @ConstructorProperties({ "id", "answerCount", "score" })
    public StackoverflowLinksRecord(@NotNull Long id, @Nullable Long answerCount, @Nullable Long score) {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);

        setId(id);
        setAnswerCount(answerCount);
        setScore(score);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StackoverflowLinksRecord
     */
    public StackoverflowLinksRecord(edu.java.scrapper.domain.jooq.tables.pojos.StackoverflowLinks value) {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);

        if (value != null) {
            setId(value.getId());
            setAnswerCount(value.getAnswerCount());
            setScore(value.getScore());
            resetChangedOnNotNull();
        }
    }
}
