/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowLinks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long answerCount;
    private Long score;

    public StackoverflowLinks() {}

    public StackoverflowLinks(StackoverflowLinks value) {
        this.id = value.id;
        this.answerCount = value.answerCount;
        this.score = value.score;
    }

    @ConstructorProperties({ "id", "answerCount", "score" })
    public StackoverflowLinks(
        @NotNull Long id,
        @Nullable Long answerCount,
        @Nullable Long score
    ) {
        this.id = id;
        this.answerCount = answerCount;
        this.score = score;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ANSWER_COUNT</code>.
     */
    @Nullable
    public Long getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Long answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.SCORE</code>.
     */
    @Nullable
    public Long getScore() {
        return this.score;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.SCORE</code>.
     */
    public void setScore(@Nullable Long score) {
        this.score = score;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StackoverflowLinks other = (StackoverflowLinks) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.answerCount == null) {
            if (other.answerCount != null)
                return false;
        }
        else if (!this.answerCount.equals(other.answerCount))
            return false;
        if (this.score == null) {
            if (other.score != null)
                return false;
        }
        else if (!this.score.equals(other.score))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        result = prime * result + ((this.score == null) ? 0 : this.score.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StackoverflowLinks (");

        sb.append(id);
        sb.append(", ").append(answerCount);
        sb.append(", ").append(score);

        sb.append(")");
        return sb.toString();
    }
}
