/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Assignment;
import edu.java.scrapper.domain.jooq.tables.Chats;
import edu.java.scrapper.domain.jooq.tables.GithubLinks;
import edu.java.scrapper.domain.jooq.tables.Links;
import edu.java.scrapper.domain.jooq.tables.StackoverflowLinks;
import edu.java.scrapper.domain.jooq.tables.records.AssignmentRecord;
import edu.java.scrapper.domain.jooq.tables.records.ChatsRecord;
import edu.java.scrapper.domain.jooq.tables.records.GithubLinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.StackoverflowLinksRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AssignmentRecord> CONSTRAINT_5 = Internal.createUniqueKey(Assignment.ASSIGNMENT, DSL.name("CONSTRAINT_5"), new TableField[] { Assignment.ASSIGNMENT.ID }, true);
    public static final UniqueKey<AssignmentRecord> CONSTRAINT_5A15 = Internal.createUniqueKey(Assignment.ASSIGNMENT, DSL.name("CONSTRAINT_5A15"), new TableField[] { Assignment.ASSIGNMENT.CHAT_ID, Assignment.ASSIGNMENT.LINK_ID }, true);
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<GithubLinksRecord> CONSTRAINT_3A6 = Internal.createUniqueKey(GithubLinks.GITHUB_LINKS, DSL.name("CONSTRAINT_3A6"), new TableField[] { GithubLinks.GITHUB_LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.URI }, true);
    public static final UniqueKey<StackoverflowLinksRecord> CONSTRAINT_1C = Internal.createUniqueKey(StackoverflowLinks.STACKOVERFLOW_LINKS, DSL.name("CONSTRAINT_1C"), new TableField[] { StackoverflowLinks.STACKOVERFLOW_LINKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AssignmentRecord, ChatsRecord> CONSTRAINT_5A = Internal.createForeignKey(Assignment.ASSIGNMENT, DSL.name("CONSTRAINT_5A"), new TableField[] { Assignment.ASSIGNMENT.CHAT_ID }, Keys.CONSTRAINT_3, new TableField[] { Chats.CHATS.ID }, true);
    public static final ForeignKey<AssignmentRecord, LinksRecord> CONSTRAINT_5A1 = Internal.createForeignKey(Assignment.ASSIGNMENT, DSL.name("CONSTRAINT_5A1"), new TableField[] { Assignment.ASSIGNMENT.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<GithubLinksRecord, LinksRecord> CONSTRAINT_3A = Internal.createForeignKey(GithubLinks.GITHUB_LINKS, DSL.name("CONSTRAINT_3A"), new TableField[] { GithubLinks.GITHUB_LINKS.ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<StackoverflowLinksRecord, LinksRecord> CONSTRAINT_1 = Internal.createForeignKey(StackoverflowLinks.STACKOVERFLOW_LINKS, DSL.name("CONSTRAINT_1"), new TableField[] { StackoverflowLinks.STACKOVERFLOW_LINKS.ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
}
